# Generated by Django 4.0.2 on 2022-06-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('publisher', models.CharField(max_length=50, null=True)),
                ('edition_no', models.IntegerField(null=True)),
                ('number_of_pages', models.IntegerField(null=True)),
                ('shelf_no', models.IntegerField(null=True)),
            ],
        ),
    ]
