# Generated by Django 4.0.2 on 2022-06-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_rename_publisher_book_publisher_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher_name',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='subject_name',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title_name',
            new_name='title',
        ),
    ]
